language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nehm33/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nehm33/react-test npm test -- --coverage

after_success:
  - docker build -t nehm33/multi-client ./client
  - docker build -t nehm33/multi-nginx ./nginx
  - docker build -t nehm33/multi-server ./server
  - docker build -t nehm33/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push nehm33/multi-client 
  - docker push nehm33/multi-nginx 
  - docker push nehm33/multi-server 
  - docker push nehm33/multi-worker